# Generated by Django 3.1.3 on 2020-12-03 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201201_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Some text', max_length=100, verbose_name='General description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(default=datetime.date(2020, 12, 17), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Imёage'),
        ),
    ]
