# Generated by Django 3.1.3 on 2020-12-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201203_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=100, verbose_name='General description'),
        ),
    ]
