from django.urls import path

from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('products/', ProductsView.as_view(), name='Products'),
    path('product/<int:pk>', ProductByIdView.as_view(), name='Product'),
    path('add_product/', CreateProductView.as_view(), name='Add_Product'),
    path('edit_product/<int:pk>', EditProductView.as_view(), name='Edit_Product'),
    path('delete_product/<int:pk>', DeleteProductView.as_view(), name='Delete_Product'),
    path('clients/', ClientsView.as_view(), name='Clients'),
    path('client/<int:pk>', ClientByIdView.as_view(), name='Client'),
    path('add_client/', CreateClientView.as_view(), name='Add_Client'),
    path('edit_client/<int:pk>', EditClientView.as_view(), name='Edit_Client'),
    path('delete_client/<int:pk>', DeleteClientView.as_view(), name='Delete_Client'),
    path('orders/', OrdersView.as_view(), name='Orders'),
    path('order/<int:pk>', OrderByIdView.as_view(), name='Order'),
    path('add_order/', CreateOrderView.as_view(), name='Add_Order'),
    path('edit_order/<int:pk>', EditOrderView.as_view(), name='Edit_Order'),
    path('delete_order/<int:pk>', DeleteOrderView.as_view(), name='Delete_Order'),
    path('categories/', CategoriesView.as_view(), name='Categories'),
    path('category/<int:pk>', CategoryByIdView.as_view(), name='Category'),
    path('add_category/', CreateCategoryView.as_view(), name='Add_Category'),
    path('edit_category/<int:pk>', EditCategoryView.as_view(), name='Edit_Category'),
    path('delete_category/<int:pk>', DeleteCategoryView.as_view(), name='Delete_Category'),
    path('supplies/', SuppliesView.as_view(), name='Supplies'),
    path('supply/<int:pk>', SupplyByIdView.as_view(), name='Supply'),
    path('providers/', ProvidersView.as_view(), name='Providers'),
    path('provider/<int:pk>', ProviderByIdView.as_view(), name='Provider'),
    path('report/', ReportView.as_view(), name='Report'),
    path('export-pdf/', export_pdf, name='Export_PDF'),
    path('login/', user_login, name='login'),
    path('logout/', user_logout, name='logout'),
    path('queries/', QueriesIndexView.as_view(), name='queries'),
    path('query1/', get_count_employees, name='get_count_employees'),
    path('query2/', get_products_by_provider_name, name='get_product_by_provider_name'),
    path('query3/', get_products_where_price_more, name='get_products_where_price_more'),
    path('query4/', get_products_in_shop, name='get_products_in_shop'),
]
